package autocode

import "github.com/flipped-aurora/gin-vue-admin/server/service/common"

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleService
	CmsCatArtService
	CmsCatService
	BasicFileService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

var commFileService = new(common.CommonFileService)
