package autocode

import "github.com/flipped-aurora/gin-vue-admin/server/service"

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	CmsCatApi
	BasicFileApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

var commDbService = service.ServiceGroupApp.CommonServiceGroup.CommDbService
