apiVersion: v1
kind: Service
metadata:
  name: gin-vue-admin-service
  annotations:
    kubesphere.io/description: gin-vue-admin service
  labels:
    app: gin-vue-admin-service
spec:
  type: NodePort
  ports:
    - name: server
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: gin-vue-admin-fe
