package common

import "github.com/flipped-aurora/gin-vue-admin/server/service"

type ApiGroup struct {
	// Code generated by gin-vue-admin Begin; DO NOT EDIT.
	CommDbApi
	FileApi
	// Code generated by gin-vue-admin End; DO NOT EDIT.
}

var commDbService = service.ServiceGroupApp.CommonServiceGroup.CommDbService

var commFileService = service.ServiceGroupApp.CommonServiceGroup.CommFileService
